### ISSUE TITLE
Update design of landing page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1160]
# Description

Update the design of the landing page to the specifications of the graphic designer.

# Tasks

- [x] Create  a new branch called ui-design-2021
- [x] Main content (#1298)
- [ ] Highlight projects (sprint-2021-04-22)
- [x] Minor fixes (sprint-2021-05-14)

# Minor fixes

- *Login* and *Sign Up* buttons in the top menu
- Change green text in first section to "Renku in an open-source project that bridges the gaps to make data-driven workflows more collaborative."
- Remove contact information from the last section and change it to be about SDSC/Renku's connection to ETH Zürich and EPFL
- Add a contact form?
- Include testimonials or examples of places using Renku
- `rk-info` needs to be switched to `rk-pink`

**Comment by ableuler** [comment]
This looks really nice already. Two suggestions from my side:

1. The fact that Renku is an open source project should be emphasized prominently on the landing page, from example here: 
![image](https://user-images.githubusercontent.com/13014091/115407907-b8d32380-a1f0-11eb-92ee-247100fab31f.png)

"Renku is an open source project that..." But I think it could also go to other locations. GitLab mention 6 times on their landing page that they are an open project.

2. There could be a preview of public projects available under some explore section when scrolling down the page.

**Comment by ciyer** [comment]
Considering this completed. We can revisit in a new issue if necessary.
