### ISSUE TITLE
Update look of top bar, search, project

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1241]
# Description

Start applying the new design to the:
- top bar (though we want to use "session" and not "pod" as the term here)
- project search
- dataset search
- project view

# Assets

https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/1337622531/Design+Assets

# Tasks (sprint 2021-02-19)
- [ ] Look in detail at the Adobe XD assets, think about what is necessary to apply the new design to the UI and provide feedback to the designer if necessary

# Tasks (sprint-2021-03-15)

- [x] Update top bar
- [x] Update footer
- [x] Update project search
- [x] Update dataset search
- [x] Update environments
- [x] Update help page
- [x] Update Login (separate issue)
- [x] Update project view
- [x] Update notifications

# Review with Luca 
- [ ] Round 2 with corrections

# Final review by Luca?

**Comment by ciyer** [comment]
This can be considered completed.
