### ISSUE TITLE
Release UI 1.0.0

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1469]
# Tasks

- [x] Banner for returning to old UI (see below)
- [x] UI changes page (see below)
- [ ] Make UI 0.11.x the canary and 1.0.0 the main UI

# Banner

Add a banner notifying the user that the UI has changed.

![image](https://user-images.githubusercontent.com/1196411/130936243-8b2eca84-6817-44cc-b99b-b7248c8c6be3.png)

# Changes Page

Add a page, taken from the landing, explaining what has changed. Next to the button to return to the old UI, there should be a link to discourse so the user can provide feedback if they prefer the old UI.

![image](https://user-images.githubusercontent.com/1196411/130938154-dc755066-bd97-4bd4-b089-0342aaa58ab6.png)
