### ISSUE TITLE
Post-Apr 20 UI Milestone

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#156]
# General
- [ ] Improve URL scheme (#167)

# Projects
- [x] Support creating projects (#129)
- [ ] Project main page should include a summary of the content: notebooks, data, code (#112)
- [ ] Initialize a project in UI (templates? Gitlab-ci, .renga metadata etc.;) (#129)
- [ ] URLs for project pages should use the namespace and project name, not the project number. E.g., "projects/cramakri/weather_ch", not "projects/1"
- [ ] Include a summary of the content in the main page (#112)

# Kus
- [ ] It should be possible to edit the text of a Ku/contribution (#108)
- [ ] The content should have multiple tabs: discussion, events (which shows "system" notes)

# Notebook Server
- [ ] Add the ability to control the notebook server ( #151)

# Misc UI Improvements
- [ ] Add Markdown help link in edit views
- [ ] Add page for maintaining SSH keys

# Refactoring
- [ ] Use index.js everywhere
- [x] Improvements to Model (#155)
- [ ] Use Model everywhere, in particular use it in components (this should simplify ```mapStateToProps```)
- [ ] Use propTypes to add some static typing to components

**Comment by ciyer** [comment]
This issue has been superseded.
