### ISSUE TITLE
21 Jun Renku Tutorial

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#222]
- [x] Improve landing page (#221)
- [ ] Improve file tab structure (#220)
- [x] Branch / merge workflow for notebooks (#223)

**Comment by erbou** [comment]
This Renku tutorial is now over. A new issue will be created for the next tutorial.
