### ISSUE TITLE
Use prettier to keep code formatting coherent

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2427]
## Description

We set up some rules through our linter to [impose constraints on code formatting](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/.eslintrc.json#L27).
That approach is not the best since the style is not coherent everywhere.

We should consider dropping all the formatting rules and switching to a proper formatter like [Prettier](https://prettier.io/)

## Tasks

That requires a few steps:
* [ ] Evaluate alternatives (Prettier seems to be the most used; double check alternatives to be sure we don't miss something obvious)
* [ ] Install the packages, remove the stale `ESlint` rules, and replace (or drop) them.
* [ ] Adjust all the files. Typically, the `--fix` command doesn't handle everything.
