### ISSUE TITLE
User UI Feedback

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#364]
Talking to data scientists who use Renku, we received the following requests:

# File View
- Provide a hierarchical view of the files. Currently this is flatten. The hierarchy should be flattened if there only < 6 entries in a further level, otherwise show hierarchically.
- Files should be badged "LFS" if they are in LFS

# Pending Changes 
- Provide a hide button on the pending changes notifications
- Remove the notifications after 30s
- [X] Always display the pending changes notification bar in the Pending Changes tab (#363)

# Jupyter Integration
- Launch Jupyter on the current commit at time of launch, not at the time the page was opened

# General
- [x] If the project is a fork, show where it was forked from (#365)
- [x] Show on the overview page information similar to what is shown in Github (number of commits, branches) (#365)
- [x] View in GitLab does not work if the page has not finished loading (#365)
