### ISSUE TITLE
Clean-up the functionality to open a notebook in JupyterLab

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#462]
The functionality around opening a notebook in JupyterLab currently has a few small things to fix:

- [ ] Have a tooltip on the JupyterLab icon also for the case where a server is running and the user is logged in.

- [x] If the user has not the required access rights, do not display the JupyterLab icon. (#531)

- [x] If the user has the required access rights but not server is running, clicking the JupyterLab icon should bring the user to the notebook launch page. (#428)

- [x] The "button" option of `LaunchNotebookButton` does not seem to be in use anymore. If so, remove this code.

- [x] Remove all traces of the `NotebookServerAPI` prop - it should not be used anymore.

- [ ] Properly update state information about running notebook servers after successful notebook launch. Currently, one needs to switch project or even reload the entire page to get the state updated. (#416)

**Comment by lorenzo-cavazzi** [comment]
Point 3 is covered by #428 at point 2.

To address 3 and 6, wait for #416 to be closed. It will enrich `Notebooks` pages with functions to check for running servers.

**Comment by lorenzo-cavazzi** [comment]
#556 address all the points except the first (it sounds like a lot of work for a feature that is marginal) and the last one that will be addressed later.
I suggest closing this issue when the aforementioned PR will be closed and open a new issue for the last point.
Feel free to open a new issue for the first point if you think it's important.

**Comment by lorenzo-cavazzi** [comment]
Last point moved to #559, other points addressed by #556
