### ISSUE TITLE
Refactor (project): component state cleanup

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#623]
We have too many redux stores; we should have just one redux store for the entire application. If a component needs local state, it should use react hooks.

While doing this, we should also reduce to a minimum the information passed to sub-components of the project page. Currently, they get the full project state, but they should only receive what they need.

Here are the locations where stores are created:

*createStore*
- [X] index.js: user --> #632 
- [x] Landing.js: Home --> #1180

*StateKind.REDUX*
- [X] Notebooks.state.js: NotebooksModel --> #627 
- [ ] DatasetList.state.js: DatasetListModel --> #1182
- [x] ProjectFork.container.js: Fork --> #1118
- [x] ProjectList.state.js: ProjectListModel --> #1181
- [ ] Project.js: View --> #1183
- [x] ProjectNew.container.js: New --> closed by #963

*mix*
- [x] Issue.js / CollaborationList --> #624 

*StateKind.REACT*
- [ ] QuickNav.container.js: QuickNavContainerWithRouter --> this doesn't necessarily need to be moved since data are stored in a local react state. We may still want to move it to the global redux store, but I can't see many synergies now (that may change with a search bar using a KG query)

**Comment by lorenzo-cavazzi** [comment]
A couple of ideas to keep in mind while moving to a single redux store:

* gradually move nested data to the first level if it's feasible. E.G. from this:
	```
	projects: {
	  project: {
		commits: {},
		branches: {}
	  }
	}
	```
	to this:
	```
	{
		projects: {},
		project: { id:123, ... }
		branches: { projectId:123, ... }
		commits: { projectId:123, branch:"master", ... }
	}
	```
	The main benefit is that it's easier for components to `mapStateToProps` to a specific topic. It's also easier to handle stale updates after involking an API

* stop using `setUpdating`/ `"is_updating"` as defined in `Models.js` because it overwrites the object values and it's generally not desirable.
Instead, try to use an extra property `status: { fetched: <timestemp>,  fetching: <bool>}` as suggested in #225

* As a general rule, we can try to keep in the `redux` store all the data coming from the backend and map them to props directly where needed instead of passing props down (this avoids undesired refreshes). All the other data (usually temporary data or UI-related data) should be stored in `react` state/props

**Comment by lorenzo-cavazzi** [comment]
`ProjectList` and `QuickNav` may be the next step since the content seems to be about `projects` and it may share functions with the already existing `ProjectsCoordinator`

**Comment by lorenzo-cavazzi** [comment]
The cleanup here was mostly done. We need additional refractory but we will open dedicated issues for that
